### ISSUE TITLE
Off Canvas and Wrapper Movement

### ISSUE THREAD

**Issue by davidtmiller** [StartBootstrap/startbootstrap-simple-sidebar#1]
Update the template to make the content wrapper shift rather than resize on menu toggle.

**Comment by DominikAngerer** [comment]
Hello @davidtmiller I'm coming from a Stackoverflow question (http://stackoverflow.com/q/29683758/1581725) where the user facing an issue with this functionality. The Movement of the content wrapper instead of resizing causes Chrome to produce an (for us) undefined behavior of calculating the height (because it will also increase but without a specific div) you can find more information about this problem here: http://stackoverflow.com/q/29683758/1581725

We thought about a bug with Chrome not directly with your implementation - but maybe you can also have a look at it - just to be sure.

Thanks.
