### ISSUE TITLE
Collapse Sidebar to icons

### ISSUE THREAD

**Issue by themeaningofmeaning** [StartBootstrap/startbootstrap-simple-sidebar#50]
How would we change the CSS to collapse the sidebar to a small width, rather than hide it (i.e. it would contain icons rather than text). I am using a webview on the right and need to have a toggle button inside of the navbar so I can expand and collapse it.

How would we preserve the integrity of your code and add that ability?

**Comment by davidtmiller** [comment]
It would require quite a bit of custom code. I may be able to tackle this in the new BS4 build I'll be working on soon.

**Comment by weiserhei** [comment]
Today I found myself in need for a collapsible sidebar and found this. Since I also wanted a 'collapse to icon' or some other kind of visible clue I hacked something together:
 https://codepen.io/anon/pen/rpmLLz

Added an```<a>```-Element which is hidden by default and toggles with the sidebar. Works on my pc, not tested. 

@davidtmiller looking forward for your bootstrap 4 release that can do this, I really like your templates!

**Comment by ghost** [comment]
@weiserhei thank you for adding that collapsed view! these suggestions might be basic, but when a new page loads it sadly automatically expands the menu again and it would be nice to see icons on collapse. i will tinker with it but my front end skills are non-existent.

**Comment by davidtmiller** [comment]
Looks like this was answered, thanks!
